### PR TITLE
Add recipe for python-levenshtein

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by johanneskoester** [comment]
Nice. Can you also add a summary so that users will see a description in the package list?

Thanks!

**Comment by kyleabeauchamp** [comment]
Done

**Comment by kyleabeauchamp** [comment]
Fixed bug, now passing.

**Comment by johanneskoester** [comment]
Nice work. Wan't to join the team? Then you can also merge yourself.

**Comment by kyleabeauchamp** [comment]
Works for me.

**Pull request merged**
