### PR TITLE
Add rsem

### PR DESCRIPTION
**Pull request by percyfal**
From install instructions:

"To install, simply put the rsem directory in your environment's PATH variable.

If you prefer to put all RSEM executables to a bin directory, please
also remember to put 'rsem_perl_utils.pm' and 'WHAT_IS_NEW' to the
same bin directory. 'rsem_perl_utils.pm' is required for most RSEM's
perl scripts and 'WHAT_IS_NEW' contains the RSEM version
information."

I currently put the binaries in $PREFIX/bin, even if WHAT_IS_NEW feels
like a generic name that could be overwritten and thus break rsem.
Should packages like this instead live in e.g. /envs/share/rsem? The end
user would then need to setup PATH.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Yeah, I hate such "broken" software. What about providing a script ``rsem`` under ``$PREFIX/bin``. The script invokes the real ``rsem``, which is located under ``$PREFIX/lib/rsem/...``?

**Comment by johanneskoester** [comment]
The script solution looks good. Let's merge.

**Comment by percyfal** [comment]
Ok, great. Will you do the honours? I'm not sure whether I should have permission to merge or not (I don't at present)?

**Comment by johanneskoester** [comment]
You should have. Do you see the merge button? If so, feel free to merge yourself.

**Comment by percyfal** [comment]
Nope, no merge button here I'm afraid.

**Comment by percyfal** [comment]
My bad, I had missed to answer the confirmation mail. Sorry about the noise.

**Pull request merged**
