### PR TITLE
Add string graph assembler (sga)

### PR DESCRIPTION
**Pull request by percyfal**
Ok, first attempt at building a conda recipe. I uploaded (prematurely?) to bioconda and managed to install so looks ok.

What is/will be the general procedure for adding packages? PRs that get accepted once the travis build is ok?

### CODE REVIEW

**Comment by johanneskoester** [comment]
Hi Per,
thanks! Exactly. We are about to merge a pull request that allows fully automatic builds, tests and uploads of all recipes. Once the merge is done, we can merge your pull request (likely tomorrow), and the package will be uploaded to the bioconda channel automatically.

**Comment by johanneskoester** [comment]
Hi,
the build system changes have been merged into master. Can you sync your branch with current master? If the checks pass, we are ready for merging.

**Comment by percyfal** [comment]
Ditto (see #10) - move sga to recipes.

**Comment by percyfal** [comment]
Checks have passed but I don't think I have permission to merge.

**Pull request merged**
