### PR TITLE
Add jellyfish 

### PR DESCRIPTION
**Pull request by percyfal**
Here's a case where feedback would be appreciated. jellyfish depends on yaggo, a small ruby gem by the same developer. My guess is that jellyfish is the only application to depend on yaggo. What's the policy in a case like this - bundle yaggo directly in the build of jellyfish or add it as its own package, as I've done now?

### CODE REVIEW

**Comment by johanneskoester** [comment]
Hi,
I have thought about this in the case of STAR-Fusion as well, and decided to create separate packages. We can never know for what they will be needed in the future. Hence, this appears to be the cleanest approach.

**Comment by johanneskoester** [comment]
Hi,
the build system changes have been merged into master. Can you sync your branch with current master? If the checks pass, we are ready for merging.

**Comment by percyfal** [comment]
Apparently I added these to the wrong directory - I recall you sending out a message just as I was finishing the package. Still, the tests passed.

**Comment by johanneskoester** [comment]
Yes, because the tests are only conducted on the recipes subdir. So they just ignored the stuff. In the future, this won't be a problem I guess.

**Comment by tomkinsc** [comment]
Looks like this needs autoreconf from the autoconf package. I'll add it to the Dockerfile.

**Comment by tomkinsc** [comment]
Ok, autoreconf is in the Docker build. Should autoconf should be added to the recipe?

**Comment by percyfal** [comment]
Yes, I'm in the process of testing it myself. It also needs libtools.

**Comment by percyfal** [comment]
Didn't see your last comment - how would you add a system dependency via the recipe if that dependency is not on conda?

**Comment by johanneskoester** [comment]
I think as long as we are not talking about libraries to build against, we can leave them out of the requirements.

**Comment by percyfal** [comment]
Not quite sure I understood your comment @johanneskoester   - I added libtool to docker. I could generate the image so I'm assuming it's ok (but mind you I'm new to docker too...). Moreover, I obviously had to move the yaggo recipe to a separate PR ( #35 ) since jellyfish depends on it to build.

**Comment by johanneskoester** [comment]
My idea was: if we have a build requirement where the version does not have an effect on the resulting binary, we can also just add it to docker instead of uploading a conda package. On the other hand, this could cause additional effort on OSX, so I would say it is also good to upload the package to bioconda like you did.

**Comment by johanneskoester** [comment]
The yaggo thing is correct.

**Comment by percyfal** [comment]
Sigh. The version of automake that gets installed in docker (1.9 ) is too old it turns out. It's difficult say in what version the missing macros (e.g. AM_COND_IF) where introduced, but 1.15 works. There is a conda package for automake but not in main channels, only channel asmeurer. So the docker tests will fail but install should work on newer systems. What are the options here:

1. make a bioconda package for automake-1.15
2. install automake-1.15 in the docker image (with rpm install)
3. skip this package for now?

**Comment by johanneskoester** [comment]
I would say we should add our own automake package into bioconda then.

**Comment by chapmanb** [comment]
As an FYI, I pushed a PR to get the latest libtools into the default Docker image. This would hopefully resolve the build issues here, and skips us needing to maintain base system packages like this which seems like a lot of work to me. If we agree to pull this all in then hopefully it'll make this possible to get in.

**Comment by percyfal** [comment]
Brad,

I think this would be a good idea. Unfortunately, it doesn't solve the jellyfish installation. I built the docker image and tested the build, getting this error in the process:

```
./configure: line 15511: syntax error near unexpected token `VALGRIND,\'
./configure: line 15511: ` PKG_CHECK_MODULES(VALGRIND, valgrind >= 1.8.0)\'
```

This has been reported before [here](https://www.biostars.org/p/103925/) and [here](https://lists.debian.org/debian-mentors/2014/10/msg00097.html). I've been trying various solutions for a while now but I simply cannot get it to work. I'll give it another shot later on.

**Comment by percyfal** [comment]
Update: the macro PKG_CHECK_MODULES wasn't expanded due to autoreconf not finding the file pkg.m4. I now manage to test jellyfish in the docker container, provided that I add package dependencies pkg-config (channel asmeurer) and ruby (channel dgc) and modify the autoreconf command to 

```
autoreconf -i $PREFIX/share/aclocal
```

This would require recipes for pkg-config and ruby, the latter which btw should be a dependency for yaggo.

**Comment by johanneskoester** [comment]
I would say we should try to setup pkg-config properly in the docker container and add ruby as a package to bioconda, just like we have already done with perl.

**Comment by chapmanb** [comment]
Agreed. You can add pkg-config to the build container with `yum install pkgconfig`, apologies for missing this with the other build tools. For the pre-existing ruby package you can copy packages you want into the bioconda channel without needing to re-build them here with `anaconda copy`. Hope this fixes it -- jellyfish seems like a tough one.

**Comment by percyfal** [comment]
Almost there. The last error I don't get. There are currently two build versions of yaggo in the bioconda channel. I was under the impression conda would always grab the latest build - why else would there be incremental build numbers? At least, this is what I get when I run it locally. However, in the docker image, the first (0) build is grabbed: 

https://travis-ci.org/bioconda/recipes/jobs/85064905#L195

**Comment by johanneskoester** [comment]
I would have thought the same. Brad, Ryan, any idea?

**Comment by chapmanb** [comment]
That's strange, I get the latest -1 version if I try to install yaggo locally. I'm not sure what is going on. My only idea would be try it again and see if that works. Sorry to not have anything more helpful than that.

**Comment by daler** [comment]
I haven't seen this either. Maybe a `conda clean` before building? But I wouldn't think there would be anything in the cache on a fresh docker container.

Possibly related: [this log line](https://travis-ci.org/bioconda/recipes/jobs/85064905#L184) says ruby can't be found. Checking the history for the yaggo `meta.yaml`, I see that build=0 yaggo does not have ruby as a dependency, but build=1 yaggo does. Maybe conda sees that ruby isn't available and grabs the non-ruby-dependent build=0?

That would be strange, but it's all I can think of.

**Comment by johanneskoester** [comment]
But ruby is available in bioconda...
Is it the same if you run the docker image on your machine or does the problem only occur in travis?

**Comment by percyfal** [comment]
Same problem occurs in docker image on my machine. I'll give it another shot, but if that fails, I guess I could remove the current yaggo builds and restart from 0?

**Comment by percyfal** [comment]
Still fails locally. It would be good to know why this is happening, but shall I just remove the current yaggo builds then and submit a new yaggo PR, starting from build 0?

**Comment by johanneskoester** [comment]
I have no objections.

**Pull request merged**
