### PR TITLE
added "which" to tools installed by yum in Dockerfile

### PR DESCRIPTION
**Pull request by tomkinsc**
things like bmtagger make use of "which" to check paths. sigh.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Which paths are determined like that?

**Comment by tomkinsc** [comment]
Notably bmfilter: ftp://ftp.ncbi.nlm.nih.gov/pub/agarwala/bmtagger/bmtagger.sh (line 46)
(Currently looking at adding bmtagger to bioconda)

**Comment by johanneskoester** [comment]
So in a sense, which would be even a runtime dependency. On the other hand, it should be present in any linux distro. I am very surprised that it is not installed per default in the CentOS image.
Let's just assume it is there, or patch it away in the script. Whatever you prefer.

**Comment by tomkinsc** [comment]
I was surprised too. I had to verify it by dropping into bash in the docker image:
    `docker run -i --entrypoint /bin/bash -t bioconda/bioconda-builder`

**Pull request merged**
