### PR TITLE
add devtoolset-2-gcc-gfortran to docker container

### PR DESCRIPTION
**Pull request by daler**
along the lines of #54, this PR simply adds `devtools-2-gcc-gfortran` to the container.

`gfortran` is needed to build `bioconductor-genefilter` which in turn is a dependency of `DESeq2`.

### CODE REVIEW

**Comment by daler** [comment]
@johanneskoester I'll let you do the merge if you approve.

**Comment by johanneskoester** [comment]
Of course I approve ;-).

**Comment by daler** [comment]
Phew! :)

I think I had made changes to the Dockerfile in other commits, and didn't realize they were getting automatically built and pushed. Decided I'd err on the side of caution this time . . .

**Comment by johanneskoester** [comment]
No problem :-).

**Pull request merged**
