### PR TITLE
add libpng to docker image

### PR DESCRIPTION
**Pull request by daler**
This is required for UCSC utils to pass their tests. They are downloaded
as executables from UCSC, but the docker build env does not have libpng.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Why not depending on libpng (which is in the default anaconda channel)?

**Comment by daler** [comment]
The default libpng still fails. Turns out the UCSC tools seem to want `libpng12.so.0`, so I can get it to run if I require libpng==1.2 in the conda recipe. But commonly-used tools -- like matplotlib -- need a later version of libpng. So then matplotlib and ucsc utils could not be in the same conda env.

But it looks like if any version of libpng is already installed on the machine, then recipe building works for UCSC utils and the tools work. I don't understand why that's the case, but this PR lets the recipes pass their tests. Building locally, uploading them to a custom channel and then `conda installing` them into an environment with matplotlib and libpng 1.6 works.

I'm certainly open to other suggestions, but this was the only way I could get it to work.

**Comment by johanneskoester** [comment]
Can we build the ucsc tools from source on the libpng provided by anaconda?

**Comment by daler** [comment]
That was the original goal over on #64, but building all the tools results in 600MB of binaries.  Using the pre-built executables was going to be the easier way . . .

I'll see if there's a good way to only build a subset of the tools and will continue poking around with libpng issues to try and avoid the `yum install` on the docker image.

**Comment by johanneskoester** [comment]
That sounds good, because my feeling is that relying on a system libpng might fail for various reasons.

**Comment by daler** [comment]
More info: looks like we're hitting something like https://github.com/conda/conda/issues/1345, further suggesting building from source. I'll focus on that.

**Comment by daler** [comment]
I'm working on compiling individual programs from the UCSC utils. I can get most of the way by using the following dependencies in the recipe[s]:

```
- mysql
- libpng
- zlib
```

However, even if I include `openssl` as a dependency, the build still fails because there's no OpenSSL development headers, like in this error:

```
gcc -O -g  -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I/anaconda/envs/_build/include/libpng16  -o udc.o -c udc.c
udc.c:39:25: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
```

The canonical answer around the web is `yum install openssl-devel`. After doing that in a local `bioconda-builder` docker container, I get a successful build. So I'm able to avoid installing libpng on the image, but I don't know how to avoid installing  `openssl-devel` on the image. Any ideas?

**Comment by johanneskoester** [comment]
I have the following in my miniconda installation:
miniconda3/include/openssl/sha.h

Maybe you need to direct gcc to the include directory?

**Comment by daler** [comment]
Ah right, thanks. I was looking in anaconda/lib for some reason.

**Comment by daler** [comment]
Solved in #194

**Pull request closed without merging**
