### PR TITLE
Add bowtie

### PR DESCRIPTION
**Pull request by percyfal**

### CODE REVIEW

**Comment by johanneskoester** [comment]
Hi,
one question: is it intended to copy the scripts folder into the bin folder?

Best,
Johannes

**Comment by percyfal** [comment]
To be honest, I just modified the bowtie2 setup. I think the scripts are called internally by bowtie, so yes, they need to be in bin.

**Comment by johanneskoester** [comment]
I did not test it, but I think the command creates $PREFIX/bin/scripts/...
Shouldn't the scripts be toplevel in bin?

**Comment by percyfal** [comment]
You're right, I misread the script. I removed directories and the copy statement, which AFAICT didn't even copy anything into the scripts directory.

**Comment by johanneskoester** [comment]
Nice, let's merge it!

**Pull request merged**
