### PR TITLE
add snakemake remote depends

### PR DESCRIPTION
**Pull request by tomkinsc**
This includes conda skeleton receipes for `moto` and `filechunkio`, two PyPi packages related to Snakemake [remote file handling](https://bitbucket.org/johanneskoester/snakemake/pull-requests/34/remote-file-support-via-remote). It adds these and `boto` as dependencies to the Snakemake `meta.yaml`. The package `boto` is used for AWS calls, `moto` is used for mocking out the live AWS API for local testing, and `filechunkio` is used for chunking files for multi-part upload.

### CODE REVIEW

**Comment by tomkinsc** [comment]
It seems a few more dependencies are needed for moto itself, to be added.

**Comment by johanneskoester** [comment]
Hi Chris,
nice work! We are right now setting up our automated build system (pull request #8). Lets wait a day before merging your nice work, then they will be build automatically!

Thanks,
Johannes

**Comment by johanneskoester** [comment]
Hi,
the build system changes have been merged into master. Can you sync your branch with current master? If the checks pass, we are ready for merging.

**Comment by tomkinsc** [comment]
This seems to have an issue with dependency chaining. I'll submit the recipes individually in the right order, with a separate PR for each.

**Pull request closed without merging**
