### PR TITLE
Upgrade pysam 0.8.4

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by chapmanb** [comment]
Kyle -- thanks much for this. Could you rebase your branch against master to get it back up to date? The protections on this repo won't let me merge out of date branches.

@johanneskoester is it possible to relax this check? This update would apply cleanly to master -- do we need to restrict it to be up to the date with the latest? This could annoy folks since unless their PR gets pulled immediately any new recipes would put it out of date.

**Comment by johanneskoester** [comment]
@chapmanb unfortunately no. I can either activate the checks via travis (then it requires the branch to be up-to-date for merging, or deactivate the checks. I could however deactivate the checks for admins. We could also encourage everybody to develop inside bioconda instead of their own forks. This way, everybody of us could trigger the update.

**Comment by daler** [comment]
I've been using the latter model -- developing directly on bioconda branches instead of a fork under my own account -- and it works reasonably well.

The only problem I've found -- and it's minor -- is that if I'm too slow merging my PR into master and someone else merges into master, I have to click the update-from-master button in the PR which in turn triggers yet another test (even if my PR test was already successful).

**Comment by chapmanb** [comment]
Ryan -- that's exactly the problem here. Kyle submitted this and then folks pushed updates to the repo in the meantime. Although there are no conflicts, we can't push the merge until Kyle rebases his branch. This can be a little tricky because one of us would have to catch the update and merge it before another update, or we have to do the dance all over again.  Johannes -- overriding this for admins makes sense to me so we can avoid frustrating contributors with this back and forth.

**Comment by daler** [comment]
Brad: True. I think what Johannes was referring to is that if this PR were under bioconda, then any of us could do the merge from master. Still some dancing involved though.

**Comment by johanneskoester** [comment]
Kyle is actually a member himself, so he can also merge. But I totally get the point. Do we want to separate current bioconda members into admins and devs, or should we just generally allow the merge? So far, I thought it would be good to constrain myself with that barrier, but I must admit that I have temporarily deactivated it one or two times to get some obvious stuff done :-).

**Comment by johanneskoester** [comment]
I just lowered the barrier. Let me try the merge...

**Comment by johanneskoester** [comment]
Works. Very handy ;-). I hope that I won't make mistakes with that power. So we should maybe discuss who wants to get admin rights?

**Comment by chapmanb** [comment]
Sounds great -- it seems worth being able to work around this to avoid a lot of unnecessary merges. Happy with whatever you decide, as long as we have a pool of folks to help with this. Thanks again.

**Comment by johanneskoester** [comment]
Under the assumption that number of commits are a measure of packaging experience, I have, for now, adjusted the rights for the top three committers, namely you, Ryan and me. We can see how that works and rethink the approach later.

**Pull request merged**
