### PR TITLE
Travis ci

### PR DESCRIPTION
**Pull request by johanneskoester**
Hi guys,
I have finished the work on automatic builds and tests with Travis CI.
This pull request introduces the following changes:

* all recipes are moved to the ``recipes`` subfolder
* the Docker image is modified to include a build script that uses ``conda``  to build all recipes
* conda is configured to skip packages that are already present in bioconda in the same version
* if executed on the master branch, the script uploads all successful builds to our channel (using a private token instead of username and password)
* all failed builds/tests are reported at the end
* Travis is configured to build for both Python 3.4 and Python 2.7 and Numpy 1.8. This can be easily extended in the future.

This approach allows us to test any branch or pull request. Further the master branch will always be in sync with the bioconda channel.

Everything works now, but the pysam test fails for Python 2.7 while importing htslib. This is not really related to this branch, we just did not have a Python 2.7 build of pysam before.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Ok, I have "fixed" the pysam test, by removing some import checks that seem to be Python version specific. The simple pysam import works. Ryan, are you ok with that change?
Now the tests only fail because pybedtools cannot be compiled on Python 2.7. Looks like a ``__future__`` import is misplaced.

**Comment by daler** [comment]
Very nice!

Honestly compiling pysam has been giving me a lot of trouble recently, esp on Mac. I will need to do some more testing to see if those other imports are needed when actually using pysam. Hopefully the simpler import test will be fine.

I think one reason pybedtools failed is because it needed pysam built for py27 (see [this line](https://travis-ci.org/bioconda/recipes/jobs/83943921#L88)). But I guess since pysam comes later alphabetically, it wasn't build yet.

However, it looks like pysam for py27 was successfully [uploaded now](https://anaconda.org/bioconda/pysam/files), so maybe a re-run of the Travis tests will work.

**Comment by daler** [comment]
Also a thought on dependencies, like pybedtools depending on pysam:

If B depends on A, then perhaps the workflow should be 
- open a PR to build A
- ensure test passes, and therefore A gets uploaded to conda
- *then* open a PR to build B

**Comment by johanneskoester** [comment]
Exactly.
After restarting the build, there is still this import error in pybedtools:
```
Using /tmp/conda-build/anaconda/envs/_build/lib/python2.7/site-packages
Finished processing dependencies for pybedtools==0.7.0
Compiling /tmp/conda-build/anaconda/envs/_build/lib/python2.7/site-packages/pybedtools-0.7.0-py2.7-linux-x86_64.egg-info/scripts/pbt_plotting_example.py ...
  File "/tmp/conda-build/anaconda/envs/_build/lib/python2.7/site-packages/pybedtools-0.7.0-py2.7-linux-x86_64.egg-info/scripts/pbt_plotting_example.py", line 5
    from __future__ import print_function
SyntaxError: from __future__ imports must occur at the beginning of the file
```

Easy to fix though.

**Comment by daler** [comment]
Ah thanks. Yep, just saw that upon trying to build it myself. Building to the latest tag (0.7.1) should fix this, but I'm testing locally first. I'll push to this branch when it's done.

**Comment by johanneskoester** [comment]
Yay, it passed :-)!

**Comment by daler** [comment]
Phew!

Pysam takes 5+ mins to compile, and I tried a bunch of different things, so it took a while. In the end it was simple: Cython is required to build pysam successfully in py27. The `htslib` import test still does not work, but pybedtools doesn't need it, so that's fine.

**Comment by daler** [comment]
Also, I had missed that the new build script only uploads when testing the master branch. This is a good idea, but it means when dealing with dependencies from contributors, and assuming B depends on A, the workflow should be modified to:

- open PR for A
- wait for tests to pass on PR branch
- merge PR into master
- wait for tests to pass on master (so A will be uploaded)
- *then* open PR for B

**Comment by johanneskoester** [comment]
Yes, you are right. We should add this to the readme. Also, since this all works, we can think about removing the python based build scripts.

**Comment by daler** [comment]
Sure, I'll add some readme text.

Brad has some pure-python packages that will eventually be cross-compiled on Mac. Currently the Python build scripts do some introspection to see if a recipe looks to be pure Python. So we might want to hold onto them for now until we have a way of doing that in the existing build-packages.sh.

**Comment by johanneskoester** [comment]
Ok, I agree. Actually, Travis allows osx builds as well. I will explore this in a follow up pull request in the next days.

**Comment by johanneskoester** [comment]
I have now activated branch protection on master, which means that none of us can accidentally push a new recipe to master. Further, all pull requests are forced to pass the CI check before they can be merged with master. We will have to see if this becomes inconvenient, but given that master is directly uploaded to our channel now, I thought it might be good to add some barriers to prevent accidents.

**Comment by johanneskoester** [comment]
I have now implemented the OSX building and think the changes are ready for merging now.

**Comment by daler** [comment]
Wow, this is fantastic!

**Comment by chapmanb** [comment]
Johannes;
This is so incredible. Thanks for putting all the Travis pieces together. Brilliant.

**Comment by johanneskoester** [comment]
Thanks :-).

**Pull request merged**
