### PR TITLE
Ucsc utils

### PR DESCRIPTION
**Pull request by daler**

### CODE REVIEW

**Comment by daler** [comment]
Errors in the docker container are like:

```
./addCols: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

I can get this to work in the docker container by requiring libpng ==1.2.50 as a dependency in the recipe, but that libpng version makes matplotlib fail in the same environment.

Is this something we can add to the docker container?

**Comment by percyfal** [comment]
I see you beat me to it - I had no time for this last week but was thinking of something similar in terms of meta templates and an automation script for the process. Have you given the meta-packaging any thought or should we open that discussion in a separate issue? Great work and initiative, thanks.

**Comment by daler** [comment]
Good to know we were on the same page. I haven't given metapackaging much thought . . . I'll open another issue so that the discussion doesn't get lost in this PR.

**Comment by daler** [comment]
Closing -- #209 is a much-improved version

**Pull request closed without merging**
