### PR TITLE
Use local builds 2

### PR DESCRIPTION
**Pull request by daler**
Testing out ideas to get #106 to pass

### CODE REVIEW

**Comment by daler** [comment]
I have this working on a local docker image -- the four new, interdependent R packages build successfully in the correct toposorted order. But the PR fails since travis can't pull the new image from dockerhub.

@johanneskoester I remember you saying the docker image is built and uploaded to dockerhub, but I can't find in the source where that happens.  Would you (or someone) double-check this Dockerfile? If it looks OK I can push to dockerhub. Thanks.

**Comment by johanneskoester** [comment]
Great to hear! So moving anaconda to /tmp does the trick?? Interesting. Automatic docker builds are setup on Dockerhub upon pushes to master. I can temporarily deactivate the branch protection to merge this to master if you are sure that it works.

**Comment by daler** [comment]
Rather than /tmp per se, it was making sure linux and osx builds were using a uniform path and then making sure those paths got indexed. Previously:

- linux-64 recipes got built in the docker container, with env configured in `Dockerfile`. Anaconda installation dir was `/anaconda`
- osx-64 recipes were built by the travis env directly, env configured in `travis-setup.sh`. Anaconda installation dir was `/tmp/anaconda`.

I had to choose one path because `build-packages.py` needed to run `conda index` after each built recipe. So I arbitrarily chose `/tmp/anaconda` to use as the anaconda installation dir. In hindsight, it's a smaller change set in the Dockerifle to use `/anaconda` as the installation dir. 

I'll make that change, test, and open a PR just for the Dockerfile. Then you can disable master branch protection, merge the new dockerfile to have an image built/uploaded to dockerhub, reenable protection, and then I can work on merging the rest of these changes.

**Comment by daler** [comment]
Closing this PR because #141 has a cleaner change set, only affecting the build environment. I'll submit another PR later with the interdependent bioconductor packages.

**Pull request closed without merging**
